name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push_prod:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Get short commit hash
      id: commit_hash
      run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

    - name: Tag and push Docker image (prod)
      run: |
        IMAGE_NAME="docker.io/raju00533/backend"
        COMMIT_HASH=${{ steps.commit_hash.outputs.hash }}
        ENVIRONMENT="prod"
        TAG="${IMAGE_NAME}:${ENVIRONMENT}-${COMMIT_HASH}"
        docker build -t $TAG .
        docker push $TAG

  build_and_push_dev:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Get short commit hash
      id: commit_hash
      run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

    - name: Tag and push Docker image (dev)
      run: |
        IMAGE_NAME="docker.io/raju00533/backend"
        COMMIT_HASH=${{ steps.commit_hash.outputs.hash }}
        ENVIRONMENT="dev"
        TAG="${IMAGE_NAME}:${ENVIRONMENT}-${COMMIT_HASH}"
        docker build -t $TAG .
        docker push $TAG
  
    - name: Increase version in package.json
      run: |
        npm version patch -m "Bump version to %s"

    - name: Push changes to repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Bump version and Docker image tag"
        commit_user_name: "Raju00533"
        commit_user_email: "raju12ghimire@gmail.com"
